### ISSUE TITLE
readme issue 

### ISSUE THREAD

**Issue by Jitulteron7** [getappmap/.github#2]
<img width="1057" alt="Screenshot 2024-06-22 at 12 12 04 PM" src="https://github.com/getappmap/.github/assets/58761652/7854f376-c68a-421d-a0b5-a0c9200136ca">
"About" spelling mistake @apotterri  @Daniel-Warner-X

**Comment by apotterri** [comment]
Hi @Jitulteron7. Thanks very much for reporting this.
